# Generated by Django 3.1 on 2020-09-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRSTNAME', models.CharField(max_length=50)),
                ('LASTNAME', models.CharField(max_length=50)),
                ('DOMAIN', models.CharField(max_length=50)),
                ('EXPERIENCE', models.IntegerField()),
                ('BRANCH', models.CharField(max_length=50)),
                ('ADDRESS', models.CharField(max_length=50)),
                ('NO_OF_BATCHES', models.IntegerField()),
                ('SALARY', models.FloatField()),
            ],
            options={
                'verbose_name': 'Trainer_Info',
                'verbose_name_plural': 'Trainer_Infos',
            },
        ),
    ]
