# Generated by Django 3.1 on 2020-09-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('AGE', models.IntegerField()),
                ('DOB', models.DateField()),
                ('ADDRESS', models.CharField(max_length=50)),
                ('ACCTYPE', models.CharField(max_length=50)),
                ('BRANCH', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('AADHARNO', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BankForm',
                'verbose_name_plural': 'BankForms',
            },
        ),
    ]
